[versions]
agp = "8.11.0"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

# Este projeto em Kotlin estava apresentando erro de Versão de Gradle, e não estava querendo rodar de jeito
# nenhum devido a diferença de versões do gradle na minha Maquina em casa e a da Maquina da Fatec.
# Por isso, após tanta procura, encontrei o arquivo que defina as versões dos componentes do projeto
# incluindo a do Gradle(agp) que estava dando conflito com este projeto.
# E para resolver este problema basta apenas trocar a versão do projeto para a versão inferior suportada
# que o problema será resolvido.

# Neste caso a versão do projeto original é a 8.12.2 e a modificada para funcionar foi a 8.11.0
# realizando essa mudança e sincronizando, todos os outros componentes serão atualizados automaticamente

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

